env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Build
  #

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 30
    agents:
      queue: macos-14
    env:
      XCODE_VERSION: 15.3.0
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp_Release.ipa
      - features/fixtures/ios/output/ipa_url_bs_release.txt
    commands:
      - bundle install
      - make test-fixtures
      - bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/iOSTestApp_Release.ipa --app-id-file=./features/fixtures/ios/output/ipa_url_bs_release.txt

  #
  # BrowserStack
  #
  - label: 'Hackathon Demo'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 10
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bs_release.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: cocoa-maze-runner
        run: cocoa-maze-runner
        command:
          - "--app=@/app/build/ipa_url_bs_release.txt"
          - "--farm=bs"
          - "--device=IOS_17"
          - "--appium-version=1.21.0"
          - "--a11y-locator"
          - "--fail-fast"
          - "features/release/hackathon.feature"
    concurrency: 5
    concurrency_group: 'browserstack-app'
    concurrency_method: eager
