steps:

  - label: 'BitBar Poc - iOS 15 - batch 1'
    depends_on: "cocoa_fixture"
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/iOSTestApp.ipa"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--exclude=features/[e-z].*.feature$"
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bb"
          - "--device=IOS_15"
          - "--no-tunnel"
          - "--aws-public-ip"
    concurrency: 5
    concurrency_group: 'bitbar-ios-15'
    concurrency_method: eager

  - label: 'BitBar Poc - iOS 15 - batch 2'
    depends_on: "cocoa_fixture"
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/iOSTestApp.ipa"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--exclude=features/[a-d].*.feature$"
          - "--app=/app/build/iOSTestApp.ipa"
          - "--farm=bb"
          - "--device=IOS_15"
          - "--no-tunnel"
          - "--aws-public-ip"
    concurrency: 5
    concurrency_group: 'bitbar-ios-15'
    concurrency_method: eager

