env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Build
  #

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
      - features/fixtures/ios/output/ipa_url_bb.txt
      - features/fixtures/ios/output/ipa_url_bs.txt
    commands:
      - bundle install
      - make test-fixtures
      - bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/iOSTestApp.ipa --app-id-file=./features/fixtures/ios/output/ipa_url_bb.txt
      - bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/iOSTestApp.ipa --app-id-file=./features/fixtures/ios/output/ipa_url_bs.txt

  - label: ':bitbar: iOS 14 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_14"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 14 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_14"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 14 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_14"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 15 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_15"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 15 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_15"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 15 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_15"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 16 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_16"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 16 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_16"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2

  - label: ':bitbar: iOS 16 E2E tests batch 1'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        download: "features/fixtures/ios/output/ipa_url_bb.txt"
        upload: "maze_output/failed/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=@/app/build/ipa_url_bb.txt"
          - "--farm=bb"
          - "--device=IOS_16"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "--fail-fast"
          - "--exclude=features/[e-z].*.feature$"
    concurrency: 25
    concurrency_group: 'bitbar'
    concurrency_method: eager
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
