env:
  LANG: "en_GB.UTF-8"

steps:

  #
  # 6.26.0
  #
  - label: 'Release 6.26.0 iOS 15.0'
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=/app/build/fixture-6.26.0.ipa"
          - "--farm=bb"
          - "--device=IOS_15_0"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "features/context.feature"
          - "features/crashprobe.feature"
    retry:
      manual:
        permit_on_passed: true
    concurrency: 10
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: 'Release 6.26.0 iOS 15.1'
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=/app/build/fixture-6.26.0.ipa"
          - "--farm=bb"
          - "--device=IOS_15_1"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "features/context.feature"
          - "features/crashprobe.feature"
    retry:
      manual:
        permit_on_passed: true
    concurrency: 10
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: 'Release 6.26.0 iOS 15.2'
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=/app/build/fixture-6.26.0.ipa"
          - "--farm=bb"
          - "--device=IOS_15_2"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "features/context.feature"
          - "features/crashprobe.feature"
    retry:
      manual:
        permit_on_passed: true
    concurrency: 10
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: 'Release 6.26.0 iOS 15.3'
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=/app/build/fixture-6.26.0.ipa"
          - "--farm=bb"
          - "--device=IOS_15_3"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "features/context.feature"
          - "features/crashprobe.feature"
    retry:
      manual:
        permit_on_passed: true
    concurrency: 10
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: 'Release 6.26.0 iOS 15.4'
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=/app/build/fixture-6.26.0.ipa"
          - "--farm=bb"
          - "--device=IOS_15_4"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "features/context.feature"
          - "features/crashprobe.feature"
    retry:
      manual:
        permit_on_passed: true
    concurrency: 10
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: 'Release 6.26.0 iOS 15.5'
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=/app/build/fixture-6.26.0.ipa"
          - "--farm=bb"
          - "--device=IOS_15_5"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "features/context.feature"
          - "features/crashprobe.feature"
    retry:
      manual:
        permit_on_passed: true
    concurrency: 10
    concurrency_group: 'bitbar-app'
    concurrency_method: eager

  - label: 'Release 6.26.0 iOS 15.6'
    timeout_in_minutes: 90
    agents:
      queue: opensource
    plugins:
      artifacts#v1.9.0:
        upload: "maze_output/**/*"
      docker-compose#v4.7.0:
        pull: cocoa-maze-runner-bitbar
        run: cocoa-maze-runner-bitbar
        service-ports: true
        command:
          - "--app=/app/build/fixture-6.26.0.ipa"
          - "--farm=bb"
          - "--device=IOS_15_6"
          - "--no-tunnel"
          - "--aws-public-ip"
          - "features/context.feature"
          - "features/crashprobe.feature"
    retry:
      manual:
        permit_on_passed: true
    concurrency: 10
    concurrency_group: 'bitbar-app'
    concurrency_method: eager
