env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Build
  #

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 30
    agents:
      queue: macos-12-arm
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
      - features/fixtures/ios/output/ipa_url.txt
    commands:
      - bundle install
      - make test-fixtures
      - bundle exec upload-app --app=./features/fixtures/ios/output/iOSTestApp.ipa --app-id-file=./features/fixtures/ios/output/ipa_url.txt

  - label: 'macOS 10.15 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: macos-10.15
    plugins:
      artifacts#v1.5.0:
        download: ["features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["macOSTestApp.log", "maze_output/failed/**/*"]
    commands:
      - bundle install
      - bundle exec maze-runner
        --os=macos
        --fail-fast
        --order=random

  ##############################################################################
  #
  # Trigger more tests
  #

  - label: 'Conditionally trigger full set of tests'
    command: sh -c .buildkite/pipeline_trigger.sh
