env:
  LANG: "en_GB.UTF-8"

steps:
  ##############################################################################
  #
  # Build
  #

  - label: Build test fixtures
    key: cocoa_fixture
    timeout_in_minutes: 30
    agents:
      queue: macos-14
    env:
      XCODE_VERSION: 15.3.0
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp_Release.ipa
      - features/fixtures/ios/output/iOSTestApp_Debug.ipa
      - features/fixtures/macos/output/macOSTestApp_Release.zip
      - features/fixtures/macos/output/macOSTestApp_Debug.zip
      - features/fixtures/ios/output/ipa_url_bb_release.txt
      - features/fixtures/ios/output/ipa_url_bs_release.txt
      - features/fixtures/ios/output/ipa_url_bb_debug.txt
      - features/fixtures/ios/output/ipa_url_bs_debug.txt
    commands:
      - bundle install
      - make test-fixtures
      - bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/iOSTestApp_Release.ipa --app-id-file=./features/fixtures/ios/output/ipa_url_bb_release.txt
      - bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/iOSTestApp_Release.ipa --app-id-file=./features/fixtures/ios/output/ipa_url_bs_release.txt
      - bundle exec upload-app --farm=bb --app=./features/fixtures/ios/output/iOSTestApp_Debug.ipa --app-id-file=./features/fixtures/ios/output/ipa_url_bb_debug.txt
      - bundle exec upload-app --farm=bs --app=./features/fixtures/ios/output/iOSTestApp_Debug.ipa --app-id-file=./features/fixtures/ios/output/ipa_url_bs_debug.txt

  - label: 'ARM macOS 14 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: macos-14-1
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp_Release.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^master|next$$"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/release/breadcrumbs.feature
        --os=macos
    retry:
      manual:
        permit_on_passed: true

  - label: 'ARM macOS 14 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: macos-14-2
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp_Release.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^master|next$$"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/release/breadcrumbs.feature
        --os=macos
    retry:
      manual:
        permit_on_passed: true

  - label: 'ARM macOS 14 E2E tests'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 60
    agents:
      queue: macos-14-3
    plugins:
      artifacts#v1.5.0:
        download: "features/fixtures/macos/output/macOSTestApp_Release.zip"
        upload:
          - "macOSTestApp.log"
          - "maze_output/failed/**/*"
      test-collector#v1.10.2:
        files: "reports/TEST-*.xml"
        format: "junit"
        branch: "^master|next$$"
    commands:
      - bundle install
      - bundle exec maze-runner
        features/release/breadcrumbs.feature
        --os=macos
    retry:
      manual:
        permit_on_passed: true
